///////////////////////////////////////////////////////////
//  UserProfileForm.cs
//  Implementation of the Class UserProfileForm
//  Generated by Enterprise Architect
//  Created on:      08-ápr.-2014 21:23:32
//  Original author: balder
///////////////////////////////////////////////////////////




namespace Main {
	public class UserProfileForm {

		public UserProfileForm(){

		}

		~UserProfileForm(){

		}

	}//end UserProfileForm

}//end namespace Main