///////////////////////////////////////////////////////////
//  NewMailForm.cs
//  Implementation of the Class NewMailForm
//  Generated by Enterprise Architect
//  Created on:      08-ápr.-2014 21:23:32
//  Original author: balder
///////////////////////////////////////////////////////////




namespace Message {
	public class NewMailForm {

		public NewMailForm(){

		}

		~NewMailForm(){

		}

	}//end NewMailForm

}//end namespace Message