///////////////////////////////////////////////////////////
//  NewOfferForm.cs
//  Implementation of the Class NewOfferForm
//  Generated by Enterprise Architect
//  Created on:      08-ápr.-2014 21:23:32
//  Original author: balder
///////////////////////////////////////////////////////////




namespace Offer {
	public class NewOfferForm {

		public NewOfferForm(){

		}

		~NewOfferForm(){

		}

	}//end NewOfferForm

}//end namespace Offer