//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectingCompanies
{
    using System;
    using System.Collections.Generic;
    
    public partial class csoportok
    {
        public csoportok()
        {
            this.ajanlatok = new HashSet<ajanlatok>();
            this.ajanlatok1 = new HashSet<ajanlatok>();
            this.esemenyek = new HashSet<esemenyek>();
            this.felhasznalok1 = new HashSet<felhasznalok>();
            this.uzenetek = new HashSet<uzenetek>();
        }
    
        public int Id { get; set; }
        public string cegnev { get; set; }
        public string telephely { get; set; }
        public int cegvezeto { get; set; }
        public string levelezesi_cim { get; set; }
        public Nullable<System.DateTime> alapitas_datuma { get; set; }
        public Nullable<int> logo { get; set; }
        public string leiras { get; set; }
    
        public virtual ICollection<ajanlatok> ajanlatok { get; set; }
        public virtual ICollection<ajanlatok> ajanlatok1 { get; set; }
        public virtual felhasznalok felhasznalok { get; set; }
        public virtual kepek kepek { get; set; }
        public virtual ICollection<esemenyek> esemenyek { get; set; }
        public virtual ICollection<felhasznalok> felhasznalok1 { get; set; }
        public virtual ICollection<uzenetek> uzenetek { get; set; }
    }
}
