//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectingCompanies
{
    using System;
    using System.Collections.Generic;
    
    public partial class felhasznalok
    {
        public felhasznalok()
        {
            this.csoportok = new HashSet<csoportok>();
            this.esemenyek = new HashSet<esemenyek>();
            this.esemenyek1 = new HashSet<esemenyek>();
            this.uzenetek = new HashSet<uzenetek>();
            this.uzenetek1 = new HashSet<uzenetek>();
        }
    
        public int Id { get; set; }
        public string azonosito { get; set; }
        public string jelszo { get; set; }
        public int jogosultsagi_szint { get; set; }
        public string nev { get; set; }
        public string lakhely { get; set; }
        public string szuletesi_hely { get; set; }
        public System.DateTime szuletesi_ido { get; set; }
        public Nullable<int> csoport { get; set; }
        public string beosztas { get; set; }
        public string leiras { get; set; }
        public Nullable<int> profilkep { get; set; }
    
        public virtual ICollection<csoportok> csoportok { get; set; }
        public virtual csoportok csoportok1 { get; set; }
        public virtual ICollection<esemenyek> esemenyek { get; set; }
        public virtual ICollection<esemenyek> esemenyek1 { get; set; }
        public virtual jogosultsagi_szintek jogosultsagi_szintek { get; set; }
        public virtual kepek kepek { get; set; }
        public virtual ICollection<uzenetek> uzenetek { get; set; }
        public virtual ICollection<uzenetek> uzenetek1 { get; set; }
    }
}
