//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectingCompanies
{
    using System;
    using System.Collections.Generic;
    
    public partial class jogosultsagi_szintek
    {
        public jogosultsagi_szintek()
        {
            this.felhasznalok = new HashSet<felhasznalok>();
        }
    
        public int Id { get; set; }
        public string megnevezes { get; set; }
    
        public virtual ICollection<felhasznalok> felhasznalok { get; set; }
    }
}
