//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectingCompanies
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class nyilvantartasEntities : DbContext
    {
        public nyilvantartasEntities()
            : base("name=nyilvantartasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ajanlatok> ajanlatok { get; set; }
        public DbSet<csoportok> csoportok { get; set; }
        public DbSet<esemenyek> esemenyek { get; set; }
        public DbSet<felhasznalok> felhasznalok { get; set; }
        public DbSet<jogosultsagi_szintek> jogosultsagi_szintek { get; set; }
        public DbSet<kepek> kepek { get; set; }
        public DbSet<uzenetek> uzenetek { get; set; }
    }
}
