//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectingCompanies
{
    using System;
    using System.Collections.Generic;
    
    public partial class uzenetek
    {
        public int Id { get; set; }
        public int felado { get; set; }
        public int cimzett { get; set; }
        public bool csoportos_level { get; set; }
        public Nullable<int> csoport { get; set; }
    
        public virtual csoportok csoportok { get; set; }
        public virtual felhasznalok felhasznalok { get; set; }
        public virtual felhasznalok felhasznalok1 { get; set; }
    }
}
