///////////////////////////////////////////////////////////
//  GroupEvent.cs
//  Implementation of the Class GroupEvent
//  Generated by Enterprise Architect
//  Created on:      08-ápr.-2014 21:23:32
//  Original author: Viktor
///////////////////////////////////////////////////////////




using System;
using Adatkezelõ;
using System.Collections.Generic;
namespace Adatkezelõ {
	public class GroupEvent : Event {

		private Group group;
		private List<Group> groups;

		public GroupEvent(){

		}

		~GroupEvent(){

		}

		public Group Group{
			get{
				return group;
			}
			set{
				group = value;
			}
		}

		public List<Group> Groups{
			get{
				return groups;
			}
			set{
				groups = value;
			}
		}

	}//end GroupEvent

}//end namespace Adatkezelõ