///////////////////////////////////////////////////////////
//  Group.cs
//  Implementation of the Class Group
//  Generated by Enterprise Architect
//  Created on:      08-ápr.-2014 21:23:31
//  Original author: Viktor
///////////////////////////////////////////////////////////




using System;
using Adatkezelõ;
using System.Collections.Generic;
namespace Adatkezelõ {
	public class Group {

		private User groupAdmin;
		private List<GroupEvent> groupEvent;
		private List<Group> groups;
		private List<Offer> offers;
		private List<User> users;
		public GroupEvent m_GroupEvent;
		public Offer m_Offer;
		public GroupProfile m_GroupProfile;

		public Group(){

		}

		public User GroupAdmin{
			get{
				return groupAdmin;
			}
			set{
				groupAdmin = value;
			}
		}

		public List<GroupEvent> GroupEvent{
			get{
				return groupEvent;
			}
			set{
				groupEvent = value;
			}
		}

		public List<Group> Groups{
			get{
				return groups;
			}
			set{
				groups = value;
			}
		}

		public List<Offer> Offers{
			get{
				return offers;
			}
			set{
				offers = value;
			}
		}

		public List<User> Users{
			get{
				return users;
			}
			set{
				users = value;
			}
		}

	}//end Group

}//end namespace Adatkezelõ