///////////////////////////////////////////////////////////
//  Profile.cs
//  Implementation of the Class Profile
//  Generated by Enterprise Architect
//  Created on:      08-ápr.-2014 21:23:32
//  Original author: Viktor
///////////////////////////////////////////////////////////



using System;
using System.Drawing;

namespace Adatkezelõ {
	public class Profile {

		private Image avatar;
		private String description;

		public Profile(){

		}

		public Image Avatar{
			get{
				return avatar;
			}
			set{
				avatar = value;
			}
		}

		public String Description{
			get{
				return description;
			}
			set{
				description = value;
			}
		}

	}//end Profile

}//end namespace Adatkezelõ