///////////////////////////////////////////////////////////
//  UserEvent.cs
//  Implementation of the Class UserEvent
//  Generated by Enterprise Architect
//  Created on:      08-ápr.-2014 21:23:32
//  Original author: Viktor
///////////////////////////////////////////////////////////




using System;
using Adatkezelõ;
using System.Collections.Generic;
namespace Adatkezelõ {
	public class UserEvent : Event {

		private User user;
		private List<User> users;

		public UserEvent(){

		}

		public User User{
			get{
				return user;
			}
			set{
				user = value;
			}
		}

		public List<User> Users{
			get{
				return users;
			}
			set{
				users = value;
			}
		}

	}//end UserEvent

}//end namespace Adatkezelõ