///////////////////////////////////////////////////////////
//  AddEventDialogForm.cs
//  Implementation of the Class AddEventDialogForm
//  Generated by Enterprise Architect
//  Created on:      08-ápr.-2014 21:23:31
//  Original author: balder
///////////////////////////////////////////////////////////




namespace AddEvent {
	public class AddEventDialogForm {

		public AddEventDialogForm(){

		}

		~AddEventDialogForm(){

		}

	}//end AddEventDialogForm

}//end namespace AddEvent