///////////////////////////////////////////////////////////
//  MainForm.cs
//  Implementation of the Class MainForm
//  Generated by Enterprise Architect
//  Created on:      08-ápr.-2014 21:23:32
//  Original author: balder
///////////////////////////////////////////////////////////




namespace LoginForm {
	public class MainForm {

		public MainForm(){

		}

		~MainForm(){

		}

	}//end MainForm

}//end namespace LoginForm