///////////////////////////////////////////////////////////
//  Event.cs
//  Implementation of the Class Event
//  Generated by Enterprise Architect
//  Created on:      08-ápr.-2014 21:23:31
//  Original author: Viktor
///////////////////////////////////////////////////////////




namespace Adatkezelõ {
	public class Event {

		private User creator;
		private Date date;
		private String description;
		private String location;
		private String name;

		public Event(){

		}

		~Event(){

		}

		public User creator{
			get{
				return creator;
			}
			set{
				creator = value;
			}
		}

		public Date date{
			get{
				return date;
			}
			set{
				date = value;
			}
		}

		public String description{
			get{
				return description;
			}
			set{
				description = value;
			}
		}

		public String location{
			get{
				return location;
			}
			set{
				location = value;
			}
		}

		public String name{
			get{
				return name;
			}
			set{
				name = value;
			}
		}

	}//end Event

}//end namespace Adatkezelõ