///////////////////////////////////////////////////////////
//  GroupEvent.cs
//  Implementation of the Class GroupEvent
//  Generated by Enterprise Architect
//  Created on:      08-ápr.-2014 21:23:32
//  Original author: Viktor
///////////////////////////////////////////////////////////




using Adatkezelõ;
namespace Adatkezelõ {
	public class GroupEvent : Event {

		private Group group;
		private List<Group> groups;

		public GroupEvent(){

		}

		~GroupEvent(){

		}

		public Group group{
			get{
				return group;
			}
			set{
				group = value;
			}
		}

		public List<Group> groups{
			get{
				return groups;
			}
			set{
				groups = value;
			}
		}

	}//end GroupEvent

}//end namespace Adatkezelõ