///////////////////////////////////////////////////////////
//  GroupHandler.cs
//  Implementation of the Class GroupHandler
//  Generated by Enterprise Architect
//  Created on:      08-ápr.-2014 21:23:32
//  Original author: balder
///////////////////////////////////////////////////////////




using Adatkezelõ;
namespace Adatkezelõ {
	public class GroupHandler {

		public Group m_Group;

		public GroupHandler(){

		}

		~GroupHandler(){

		}

		public Group CreateGroup(){

			return null;
		}

		/// 
		/// <param name="groupId"></param>
		public void DeleteGroup(int groupId){

		}

		/// 
		/// <param name="groupId"></param>
		public Group getGroup(int groupId){

			return null;
		}

	}//end GroupHandler

}//end namespace Adatkezelõ