///////////////////////////////////////////////////////////
//  Message.cs
//  Implementation of the Class Message
//  Generated by Enterprise Architect
//  Created on:      08-ápr.-2014 21:23:32
//  Original author: Viktor
///////////////////////////////////////////////////////////




namespace Adatkezelõ {
	public class Message {

		private String body;
		private Date date;
		private User reciever;
		private User sender;
		private String subject;

		public Message(){

		}

		~Message(){

		}

		public String body{
			get{
				return body;
			}
			set{
				body = value;
			}
		}

		public Date date{
			get{
				return date;
			}
			set{
				date = value;
			}
		}

		public User reciever{
			get{
				return reciever;
			}
			set{
				reciever = value;
			}
		}

		public User sender{
			get{
				return sender;
			}
			set{
				sender = value;
			}
		}

		public String subject{
			get{
				return subject;
			}
			set{
				subject = value;
			}
		}

	}//end Message

}//end namespace Adatkezelõ