///////////////////////////////////////////////////////////
//  Offer.cs
//  Implementation of the Class Offer
//  Generated by Enterprise Architect
//  Created on:      08-ápr.-2014 21:23:32
//  Original author: Viktor
///////////////////////////////////////////////////////////




using Adatkezelõ;
namespace Adatkezelõ {
	public class Offer {

		private Date date;
		private String description;
		private Group destination;
		private String name;
		private Group source;

		public Offer(){

		}

		~Offer(){

		}

		public Date date{
			get{
				return date;
			}
			set{
				date = value;
			}
		}

		public String description{
			get{
				return description;
			}
			set{
				description = value;
			}
		}

		public Group destination{
			get{
				return destination;
			}
			set{
				destination = value;
			}
		}

		public String name{
			get{
				return name;
			}
			set{
				name = value;
			}
		}

		public Group source{
			get{
				return source;
			}
			set{
				source = value;
			}
		}

	}//end Offer

}//end namespace Adatkezelõ