///////////////////////////////////////////////////////////
//  UserHandler.cs
//  Implementation of the Class UserHandler
//  Generated by Enterprise Architect
//  Created on:      08-ápr.-2014 21:23:32
//  Original author: balder
///////////////////////////////////////////////////////////




namespace Adatkezelõ {
	public class UserHandler {

		public UserHandler(){

		}

		~UserHandler(){

		}

		/// 
		/// <param name="groupId"></param>
		/// <param name="userId"></param>
		public void CreateGroupAdmin(int groupId, int userId){

		}

		public User CreateUser(){

			return null;
		}

		/// 
		/// <param name="userId"></param>
		public void DeleteUser(int userId){

		}

		/// 
		/// <param name="userId"></param>
		public User GetUser(int userId){

			return null;
		}

	}//end UserHandler

}//end namespace Adatkezelõ