///////////////////////////////////////////////////////////
//  UserType.cs
//  Implementation of the Class UserType
//  Generated by Enterprise Architect
//  Created on:      08-ápr.-2014 21:23:32
//  Original author: Viktor
///////////////////////////////////////////////////////////




namespace Adatkezelõ {
	public enum UserType : int {

		Guest = 0,
		GroupUser = 1,
		GroupAdmin = 2,
		SysAdmin = 3

	}//end UserType

}//end namespace Adatkezelõ