///////////////////////////////////////////////////////////
//  User.cs
//  Implementation of the Class User
//  Generated by Enterprise Architect
//  Created on:      08-ápr.-2014 21:40:16
//  Original author: Viktor
///////////////////////////////////////////////////////////




using Adatkezelõ;
namespace Adatkezelõ {
	public class User {

		private Group group;
		private String password;
		private UserProfile profile;
		private UserType type;
		private List<UserEvent> userEvents;
		private UserName userName;
		public Group m_Group;
		public Message m_Message;

		public User(){

		}

		~User(){

		}

		public Group group{
			get{
				return group;
			}
			set{
				group = value;
			}
		}

		public String password{
			get{
				return password;
			}
			set{
				password = value;
			}
		}

		public UserProfile profile{
			get{
				return profile;
			}
			set{
				profile = value;
			}
		}

		public UserType type{
			get{
				return type;
			}
			set{
				type = value;
			}
		}

		public List<UserEvent> userEvents{
			get{
				return userEvents;
			}
			set{
				userEvents = value;
			}
		}

		public UserName userName{
			get{
				return userName;
			}
			set{
				userName = value;
			}
		}

	}//end User

}//end namespace Adatkezelõ