///////////////////////////////////////////////////////////
//  UserEvent.cs
//  Implementation of the Class UserEvent
//  Generated by Enterprise Architect
//  Created on:      08-ápr.-2014 21:23:32
//  Original author: Viktor
///////////////////////////////////////////////////////////




using Adatkezelõ;
namespace Adatkezelõ {
	public class UserEvent : Event {

		private User user;
		private List<User> users;

		public UserEvent(){

		}

		~UserEvent(){

		}

		public User user{
			get{
				return user;
			}
			set{
				user = value;
			}
		}

		public List<User> users{
			get{
				return users;
			}
			set{
				users = value;
			}
		}

	}//end UserEvent

}//end namespace Adatkezelõ